apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapp-deployment
  labels:
    app: backendapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - name: backendapp
          image: dsdatsme/nodecron
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
